### ISSUE TITLE
Milestones before Bytecode Alliance/`wasm-tools` merger

### ISSUE THREAD

**Issue by thesuhas** [thesuhas/orca#126]
- [ ] ComponentizeJS migration to Orca
- [ ] Make issue with checklist of missing opcode support (e.g. SIMD)
- [ ] Look into DWARF debug info for post-instrumentation
- [ ] Testing plan: Fuzzing, actually execute modules to test roundtrip, spec tests since they already have assertions (.bin.wast, load .bin and roundtrip it, execute that)

## Important Links:

- [Dwarf Debugging Format](https://dwarfstd.org)
- [Wasmtime Dwarf issue](https://github.com/bytecodealliance/wasmtime/issues/5537)
- [`cargo fuzz`](https://github.com/rust-fuzz/cargo-fuzz)
- [Struct-aware fuzzing (cargo fuzz)](https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html)
- [arbitrary crate](https://crates.io/crates/arbitrary)
- [`wasm-bindgen` arbitrary rust book](https://rustwasm.github.io/wasm-bindgen/reference/arbitrary-data-with-serde.html)
- [libfuzz crate](https://crates.io/crates/libfuzzer-sys)
- [`wasm-smith`](https://crates.io/crates/wasm-smith)
- [`ComponentizeJS`](https://github.com/bytecodealliance/ComponentizeJS)
- [`wasm memcheck`](https://docs.wasmtime.dev/wmemcheck.html)
